-- Recreate the permissive table/sequence defaults carried by older hosted
-- Supabase projects, then reapply the real S08 migration. This makes the test
-- fail without S08 even though vanilla PostgreSQL starts these object classes
-- closed by default. Existing objects are already present, so only future-object
-- behavior changes during this fixture.
alter default privileges for role postgres in schema public
  grant select, insert, update, delete on tables to anon, authenticated;

alter default privileges for role postgres in schema public
  grant usage, select on sequences to anon, authenticated;

\ir ../migrations/20260913201500_s08_db_object_access_gate.sql

begin;

-- Real product tenant/role fixtures. All authorization assertions below run as
-- authenticated/anon, never as the table owner or a BYPASSRLS role.
insert into auth.users(id, email, raw_user_meta_data)
values
  ('80800000-0000-0000-0000-000000000001', 's08-owner-a@example.invalid', '{"full_name":"S08 Owner A"}'::jsonb),
  ('80800000-0000-0000-0000-000000000002', 's08-staff-a@example.invalid', '{"full_name":"S08 Staff A"}'::jsonb),
  ('80800000-0000-0000-0000-000000000003', 's08-owner-b@example.invalid', '{"full_name":"S08 Owner B"}'::jsonb);

insert into public.businesses(id, name, slug, timezone, created_by)
values
  ('80810000-0000-0000-0000-000000000001', 'S08 Tenant A', 's08-tenant-a', 'Europe/Istanbul', '80800000-0000-0000-0000-000000000001'),
  ('80810000-0000-0000-0000-000000000002', 'S08 Tenant B', 's08-tenant-b', 'Europe/Istanbul', '80800000-0000-0000-0000-000000000003');

insert into public.memberships(business_id, user_id, role, active)
values
  ('80810000-0000-0000-0000-000000000001', '80800000-0000-0000-0000-000000000001', 'owner', true),
  ('80810000-0000-0000-0000-000000000001', '80800000-0000-0000-0000-000000000002', 'staff', true),
  ('80810000-0000-0000-0000-000000000002', '80800000-0000-0000-0000-000000000003', 'owner', true);

-- Disposable future-object probe. The S08 migration must make all four exposed
-- object classes deny-by-default for API roles until an explicit grant is added.
create table public.s08_acl_probe (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id),
  payload text not null
);

alter table public.s08_acl_probe enable row level security;
alter table public.s08_acl_probe force row level security;

create policy s08_acl_probe_select
on public.s08_acl_probe
for select
to authenticated
using ((select public.is_active_member(business_id)));

create policy s08_acl_probe_insert
on public.s08_acl_probe
for insert
to authenticated
with check ((select public.can_manage_business(business_id)));

create view public.s08_acl_probe_view
with (security_invoker = true)
as
select id, business_id, payload
from public.s08_acl_probe;

create function public.s08_acl_probe_invoker()
returns uuid
language sql
stable
security invoker
set search_path = ''
as $$
  select auth.uid()
$$;

create function public.s08_acl_probe_definer()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select current_user::text
$$;

-- Default privileges: neither API role may see a future table/view, consume its
-- sequence, or execute either invoker/definer function before an explicit grant.
do $$
begin
  if has_table_privilege('anon', 'public.s08_acl_probe', 'SELECT')
     or has_table_privilege('authenticated', 'public.s08_acl_probe', 'SELECT')
     or has_table_privilege('anon', 'public.s08_acl_probe', 'INSERT')
     or has_table_privilege('authenticated', 'public.s08_acl_probe', 'INSERT') then
    raise exception 'future table inherited API-role privileges';
  end if;

  if has_table_privilege('anon', 'public.s08_acl_probe_view', 'SELECT')
     or has_table_privilege('authenticated', 'public.s08_acl_probe_view', 'SELECT') then
    raise exception 'future view inherited API-role privileges';
  end if;

  if has_sequence_privilege('anon', 'public.s08_acl_probe_id_seq', 'USAGE')
     or has_sequence_privilege('authenticated', 'public.s08_acl_probe_id_seq', 'USAGE')
     or has_sequence_privilege('anon', 'public.s08_acl_probe_id_seq', 'SELECT')
     or has_sequence_privilege('authenticated', 'public.s08_acl_probe_id_seq', 'SELECT') then
    raise exception 'future sequence inherited API-role privileges';
  end if;

  if has_function_privilege('anon', 'public.s08_acl_probe_invoker()', 'EXECUTE')
     or has_function_privilege('authenticated', 'public.s08_acl_probe_invoker()', 'EXECUTE')
     or has_function_privilege('anon', 'public.s08_acl_probe_definer()', 'EXECUTE')
     or has_function_privilege('authenticated', 'public.s08_acl_probe_definer()', 'EXECUTE') then
    raise exception 'future function inherited API-role EXECUTE';
  end if;
end
$$;

-- Explicit grants open only the authenticated probe surface. The definer helper
-- deliberately remains closed to prove privileged code is not exposed by the
-- default gate.
grant select, insert on public.s08_acl_probe to authenticated;
grant usage, select on sequence public.s08_acl_probe_id_seq to authenticated;
grant select on public.s08_acl_probe_view to authenticated;
grant execute on function public.s08_acl_probe_invoker() to authenticated;

insert into public.s08_acl_probe(business_id, payload)
values
  ('80810000-0000-0000-0000-000000000001', 'tenant-a-seed'),
  ('80810000-0000-0000-0000-000000000002', 'tenant-b-seed');

-- Owner A: explicit object grants work, own tenant rows pass RLS, and tenant B
-- remains invisible. The view must preserve the same RLS boundary.
set local role authenticated;
select set_config('request.jwt.claim.sub', '80800000-0000-0000-0000-000000000001', true);

do $$
declare
  v_count integer;
  v_next bigint;
begin
  select count(*) into v_count from public.s08_acl_probe;
  if v_count <> 1 then
    raise exception 'owner A did not see exactly its own tenant row: %', v_count;
  end if;

  select count(*) into v_count
  from public.s08_acl_probe
  where business_id = '80810000-0000-0000-0000-000000000002';
  if v_count <> 0 then
    raise exception 'cross-tenant row escaped RLS';
  end if;

  select count(*) into v_count from public.s08_acl_probe_view;
  if v_count <> 1 then
    raise exception 'security_invoker view did not preserve tenant RLS: %', v_count;
  end if;

  if public.s08_acl_probe_invoker() is distinct from '80800000-0000-0000-0000-000000000001'::uuid then
    raise exception 'explicitly granted invoker function returned the wrong auth identity';
  end if;

  v_next := nextval('public.s08_acl_probe_id_seq'::regclass);
  if v_next is null then
    raise exception 'explicit sequence grant did not allow authenticated nextval';
  end if;

  insert into public.s08_acl_probe(business_id, payload)
  values ('80810000-0000-0000-0000-000000000001', 'owner-a-write');

  begin
    insert into public.s08_acl_probe(business_id, payload)
    values ('80810000-0000-0000-0000-000000000002', 'cross-tenant-forbidden');
    raise exception 'owner A unexpectedly inserted into tenant B';
  exception when insufficient_privilege then
    null;
  end;

  begin
    perform public.s08_acl_probe_definer();
    raise exception 'closed SECURITY DEFINER probe became executable';
  exception when insufficient_privilege then
    null;
  end;
end
$$;

reset role;

-- Staff A is an active member, so SELECT is allowed, but the INSERT policy uses
-- the real can_manage_business() role contract and must reject staff writes.
set local role authenticated;
select set_config('request.jwt.claim.sub', '80800000-0000-0000-0000-000000000002', true);

do $$
declare
  v_count integer;
begin
  select count(*) into v_count from public.s08_acl_probe;
  if v_count <> 2 then
    raise exception 'staff A did not read the two tenant A rows: %', v_count;
  end if;

  begin
    insert into public.s08_acl_probe(business_id, payload)
    values ('80810000-0000-0000-0000-000000000001', 'staff-write-forbidden');
    raise exception 'staff A unexpectedly passed manager-only INSERT policy';
  exception when insufficient_privilege then
    null;
  end;
end
$$;

reset role;

-- Anonymous callers stay outside every probe object even after the narrow
-- authenticated grants above. These failures occur at the object-grant layer,
-- independently of the RLS policies exercised above.
set local role anon;
select set_config('request.jwt.claim.sub', '', true);

do $$
begin
  begin
    perform 1 from public.s08_acl_probe limit 1;
    raise exception 'anon unexpectedly read future table';
  exception when insufficient_privilege then
    null;
  end;

  begin
    perform 1 from public.s08_acl_probe_view limit 1;
    raise exception 'anon unexpectedly read future view';
  exception when insufficient_privilege then
    null;
  end;

  begin
    perform nextval('public.s08_acl_probe_id_seq'::regclass);
    raise exception 'anon unexpectedly consumed future sequence';
  exception when insufficient_privilege then
    null;
  end;

  begin
    perform public.s08_acl_probe_invoker();
    raise exception 'anon unexpectedly executed future invoker function';
  exception when insufficient_privilege then
    null;
  end;

  begin
    perform public.s08_acl_probe_definer();
    raise exception 'anon unexpectedly executed future definer function';
  exception when insufficient_privilege then
    null;
  end;
end
$$;

reset role;
rollback;
